source 'https://rubygems.org'
gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'thin'
gem 'cyrax', path: '..'

# assets
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'skim'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'bootstrap-sass', github: 'thomas-mcdonald/bootstrap-sass'

gem "rspec-rails", ">= 2.12.2", :group => [:development, :test]
gem "database_cleaner", ">= 1.0.0.RC1", :group => :test
gem "email_spec", ">= 1.4.0", :group => :test
gem "factory_girl_rails", ">= 4.2.0", :group => [:development, :test]
gem "devise", ">= 3.1.0"
gem "simple_form", ">= 2.1.0"
gem "quiet_assets", ">= 1.0.2", :group => :development
gem "figaro", ">= 0.6.3"
gem "binding_of_caller", ">= 0.7.1", :group => :development, :platforms => [:mri_19, :rbx]
